name = "resume-worker"
type = "javascript"
account_id = "1a2c94ed11d35ed045d3d0bfb8a6d6b9"
workers_dev = true
compatibility_date = "2024-02-04"

[vars]
R2_BUCKET_NAME = "secure-resumes"
RESUME_NAME = "Aaron_Feingold_Software_Engineer_Resume.pdf"

[observability.logs]
enabled = true
